In [ ]:
1.0 Importing Libraries

In [3]:
#importing libraries
import pandas as pd
import numpy as np
import os

In [5]:
df_orders = pd.read_csv(r'C:\Users\Chama Chilufya\Documents\12-2024 Instacart Basket Analysis\02-Data\Original Data\orders.csv', index_col = False)

In [6]:
path = r'C:\Users\Chama Chilufya\Documents\12-2024 Instacart Basket Analysis'

In [7]:
df_orders = pd.read_csv(os.path.join(path, '02-Data', 'Original Data', 'orders.csv'), index_col = False)

In [8]:
df_prods = pd.read_csv(os.path.join(path, '02-Data', 'Original Data', 'products.csv'), index_col = False)

2.0 Dropping Columns

In [10]:
#Dropping 'eval_set' column from orders.csv
df_orders.drop(columns = ['eval_set'])

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0
...,...,...,...,...,...,...
3421078,2266710,206209,10,5,18,29.0
3421079,1854736,206209,11,4,10,30.0
3421080,626363,206209,12,1,12,18.0
3421081,2977660,206209,13,1,12,7.0
3421082,272231,206209,14,6,14,30.0

In [11]:
df_orders = df_orders.drop(columns = ['eval_set'])

In [12]:
df_orders['days_since_prior_order'].value_counts(dropna = False)

days_since_prior_order
30.0    369323
7.0     320608
6.0     240013
4.0     221696
3.0     217005
5.0     214503
NaN     206209
2.0     193206
8.0     181717
1.0     145247
9.0     118188
14.0    100230
10.0     95186
13.0     83214
11.0     80970
12.0     76146
0.0      67755
15.0     66579
16.0     46941
21.0     45470
17.0     39245
20.0     38527
18.0     35881
19.0     34384
22.0     32012
28.0     26777
23.0     23885
27.0     22013
24.0     20712
25.0     19234
29.0     19191
26.0     19016
Name: count, dtype: int64

3.0 Renaming Columns

In [14]:
df_orders.rename(columns = {'order_dow' : 'orders_day_of_week'}, inplace = True)

In [16]:
df_orders.head()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,2539329,1,1,2,8,NaN
1,2398795,1,2,3,7,15.0
2,473747,1,3,3,12,21.0
3,2254736,1,4,4,7,29.0
4,431534,1,5,4,15,28.0

4.0 Changing a Variable’s Data Type

In [17]:
df_orders.describe()

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [23]:
df_orders['order_id'] = df_orders['order_id'].astype('str')

In [26]:
df_orders['order_id'].dtype

dtype('O')

5.0 Transposing Data

In [28]:
#Importing data set department.csv
df_dep = pd.read_csv(os.path.join(path, '02-Data', 'Original Data', 'departments.csv'), index_col = False)

In [29]:
df_dep.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [30]:
#Transposing df_dep
df_dep.T

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [31]:
df_dep_t = df_dep.T

In [32]:
df_dep_t

                             0
department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

In [33]:
df_dep_t.reset_index()

            index                0
0   department_id       department
1               1           frozen
2               2            other
3               3           bakery
4               4          produce
5               5          alcohol
6               6    international
7               7        beverages
8               8             pets
9               9  dry goods pasta
10             10             bulk
11             11    personal care
12             12     meat seafood
13             13           pantry
14             14        breakfast
15             15     canned goods
16             16       dairy eggs
17             17        household
18             18           babies
19             19           snacks
20             20             deli
21             21          missing

In [34]:
#Take the first row of the df-dep_t for the header
new_header = df_dep_t.iloc[0]

In [35]:
new_header

0    department
Name: department_id, dtype: object

In [36]:
df_dep_t_new = df_dep_t[1:]

In [37]:
df_dep_t.reset_index()

            index                0
0   department_id       department
1               1           frozen
2               2            other
3               3           bakery
4               4          produce
5               5          alcohol
6               6    international
7               7        beverages
8               8             pets
9               9  dry goods pasta
10             10             bulk
11             11    personal care
12             12     meat seafood
13             13           pantry
14             14        breakfast
15             15     canned goods
16             16       dairy eggs
17             17        household
18             18           babies
19             19           snacks
20             20             deli
21             21          missing

In [38]:
#take the data under the headerrow for a new df
df_dep_t_new = df_dep_t[1:]

In [39]:
df_dep_t_new

                  0
1            frozen
2             other
3            bakery
4           produce
5           alcohol
6     international
7         beverages
8              pets
9   dry goods pasta
10             bulk
11    personal care
12     meat seafood
13           pantry
14        breakfast
15     canned goods
16       dairy eggs
17        household
18           babies
19           snacks
20             deli
21          missing

In [40]:
df_dep_t_new.columns = new_header # set the header row as the df_header

In [41]:
df_dep_t_new

department_id       department
1                       frozen
2                        other
3                       bakery
4                      produce
5                      alcohol
6                international
7                    beverages
8                         pets
9              dry goods pasta
10                        bulk
11               personal care
12                meat seafood
13                      pantry
14                   breakfast
15                canned goods
16                  dairy eggs
17                   household
18                      babies
19                      snacks
20                        deli
21                     missing

6.0 Data Dictionary

In [42]:
data_dict = df_dep_t_new.to_dict('index')

In [43]:
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [44]:
df_prods.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [45]:
print(data_dict.get('19'))

{'department': 'snacks'}

8.0 Subsetting

In [46]:
df_prods['department_id']==19

0         True
1        False
2        False
3        False
4        False
         ...
49688    False
49689    False
49690    False
49691    False
49692    False
Name: department_id, Length: 49693, dtype: bool

In [48]:
df_prods[df_prods['department_id']==19]

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5
...,...,...,...,...,...
49666,49662,Bacon Cheddar Pretzel Pieces,107,19,3.6
49669,49665,Super Dark Coconut Ash & Banana Chocolate Bar,45,19,6.9
49670,49666,Ginger Snaps Snacking Cookies,61,19,5.2
49675,49671,Milk Chocolate Drops,45,19,3.0
49683,49679,Famous Chocolate Wafers,61,19,6.0

In [49]:
df_snacks =  df_prods[df_prods['department_id']==19]

In [50]:
df_snacks.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
15,16,Mint Chocolate Flavored Syrup,103,19,5.2
24,25,Salted Caramel Lean Protein & Fiber Bar,3,19,1.9
31,32,Nacho Cheese White Bean Chips,107,19,4.9
40,41,Organic Sourdough Einkorn Crackers Rosemary,78,19,6.5

In [ ]:
                                                    EXERCISE 4.4

Question 1. Already done

In [ ]:
Question 2
#Find another identifier variable in the df_ords dataframe that doesn’t need to be included in your analysis as a numeric variable and change
it to a suitable format.

In [51]:
df_orders.describe()

,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [ ]:
I have identified order number which shouldnt be included in the analysis as numeric value and will change to a string

In [52]:
df_orders['order_number'] = df_orders['order_number'].astype('str')

In [54]:
df_orders['order_number'].dtype

dtype('O')

Question 3
Look for a variable in your df_ords dataframe with an unintuitive name and change its name without overwriting the dataframe.

In [ ]:
I have identified 'user_id' amd want to change it to 'user identity number'

In [55]:
df_orders.rename(columns = {'user_id' : 'user_identity_number'}, inplace = True)

In [56]:
df_orders.head()

,order_id,user_identity_number,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,object,1,1,2,8,NaN
1,object,1,2,3,7,15.0
2,object,1,3,3,12,21.0
3,object,1,4,4,7,29.0
4,object,1,5,4,15,28.0

Question 4
Your client wants to know what the busiest hour is for placing orders. Find the frequency of the corresponding variable and share your findings

In [58]:
df_orders['order_hour_of_day'].value_counts

<bound method IndexOpsMixin.value_counts of 0           8
1           7
2          12
3           7
4          15
           ..
3421078    18
3421079    10
3421080    12
3421081    12
3421082    14
Name: order_hour_of_day, Length: 3421083, dtype: int64>

In [ ]:
I have picked 15:00hrs ecause it has the highest order number meaning at this hour most orders are made.

Question 5
Determine the meaning behind a value of 4 in the "department_id" column within the df_prods dataframe using a data dictionary

In [59]:
data_dict = df_dep_t_new.to_dict('index')

In [60]:
data_dict

{'1': {'department': 'frozen'},
 '2': {'department': 'other'},
 '3': {'department': 'bakery'},
 '4': {'department': 'produce'},
 '5': {'department': 'alcohol'},
 '6': {'department': 'international'},
 '7': {'department': 'beverages'},
 '8': {'department': 'pets'},
 '9': {'department': 'dry goods pasta'},
 '10': {'department': 'bulk'},
 '11': {'department': 'personal care'},
 '12': {'department': 'meat seafood'},
 '13': {'department': 'pantry'},
 '14': {'department': 'breakfast'},
 '15': {'department': 'canned goods'},
 '16': {'department': 'dairy eggs'},
 '17': {'department': 'household'},
 '18': {'department': 'babies'},
 '19': {'department': 'snacks'},
 '20': {'department': 'deli'},
 '21': {'department': 'missing'}}

In [61]:
print(data_dict.get('4'))

{'department': 'produce'}

In [ ]:
The value 4 in the 'department id' data dictionary means produce

Question 6
The sales team in your client’s organization wants to know more about breakfast item sales. Create a subset containing only the required information.

In [62]:
 df_prods['department_id']==14

0        False
1        False
2        False
3        False
4        False
         ...
49688    False
49689    False
49690    False
49691    False
49692    False
Name: department_id, Length: 49693, dtype: bool

In [63]:
df_prods[df_prods['department_id']==14]

,product_id,product_name,aisle_id,department_id,prices
27,28,Wheat Chex Cereal,121,14,10.1
33,34,NaN,121,14,12.2
67,68,"Pancake Mix, Buttermilk",130,14,13.7
89,90,Smorz Cereal,121,14,3.9
210,211,Gluten Free Organic Cereal Coconut Maple Vanilla,130,14,3.6
...,...,...,...,...,...
49330,49326,Cereal Variety Fun Pack,121,14,9.1
49395,49391,Light and Fluffy Buttermilk Pancake Mix,130,14,2.0
49547,49543,Chocolate Cheerios Cereal,121,14,10.8
49637,49633,Shake 'N Pour Buttermilk Pancake Mix,130,14,14.2
49667,49663,Ultra Protein Power Crunch Peanut Butter N' Ho...,57,14,10.2

In [64]:
df_breakfast = df_prods[df_prods['department_id']==14]

In [65]:
df_breakfast.head()

,product_id,product_name,aisle_id,department_id,prices
27,28,Wheat Chex Cereal,121,14,10.1
33,34,NaN,121,14,12.2
67,68,"Pancake Mix, Buttermilk",130,14,13.7
89,90,Smorz Cereal,121,14,3.9
210,211,Gluten Free Organic Cereal Coconut Maple Vanilla,130,14,3.6

Question 7 
They’d also like to see details about products that customers might use to throw dinner parties. Your task is to find all observations from the
entire dataframe that include items from the following departments: alcohol, deli, beverages, and meat/seafood.
You’ll need to present this subset to your client.

In [ ]:
The identified variables include: alcohol = 5, deli = 20, beaverages = 7 and meat/seafood = 12

In [73]:
df_prods['department_id'].isin([5,20,7,12])

0        False
1        False
2         True
3        False
4        False
         ...
49688     True
49689    False
49690    False
49691    False
49692    False
Name: department_id, Length: 49693, dtype: bool

In [75]:
df_prods[df_prods['department_id'].isin([5,20,7,12])]

,product_id,product_name,aisle_id,department_id,prices
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
6,7,Pure Coconut Water With Orange,98,7,4.4
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.4
10,11,Peach Mango Juice,31,7,2.8
16,17,Rendered Duck Fat,35,12,17.1
...,...,...,...,...,...
49676,49672,Cafe Mocha K-Cup Packs,26,7,6.5
49679,49675,Cinnamon Dolce Keurig Brewed K Cups,26,7,14.0
49680,49676,Ultra Red Energy Drink,64,7,14.5
49686,49682,California Limeade,98,7,4.3
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3

In [81]:
df_assortedprods = df_prods[df_prods['department_id'].isin([5,20,7,12])]

In [82]:
df_assortedprods

,product_id,product_name,aisle_id,department_id,prices
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
6,7,Pure Coconut Water With Orange,98,7,4.4
9,10,Sparkling Orange Juice & Prickly Pear Beverage,115,7,8.4
10,11,Peach Mango Juice,31,7,2.8
16,17,Rendered Duck Fat,35,12,17.1
...,...,...,...,...,...
49676,49672,Cafe Mocha K-Cup Packs,26,7,6.5
49679,49675,Cinnamon Dolce Keurig Brewed K Cups,26,7,14.0
49680,49676,Ultra Red Energy Drink,64,7,14.5
49686,49682,California Limeade,98,7,4.3
49688,49684,"Vodka, Triple Distilled, Twist of Vanilla",124,5,5.3

Question 8
It’s important that you keep track of total counts in your dataframes. How many rows does the last dataframe you created have?

In [ ]:
Based the newly created dataframe the number of rows created are 7650 rows occupying 5 columns

In [ ]:
Question 9
Someone from the data engineers team in Instacart thinks they’ve spotted something strange about the customer with a "user_id" of “1.” 
Extract all the information you can about this user

In [91]:
data_dictionary = df_orders.to_dict('index')

In [92]:
data_dictionary

{0: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '1',
  'orders_day_of_week': 2,
  'order_hour_of_day': 8,
  'days_since_prior_order': nan},
 1: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '2',
  'orders_day_of_week': 3,
  'order_hour_of_day': 7,
  'days_since_prior_order': 15.0},
 2: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '3',
  'orders_day_of_week': 3,
  'order_hour_of_day': 12,
  'days_since_prior_order': 21.0},
 3: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '4',
  'orders_day_of_week': 4,
  'order_hour_of_day': 7,
  'days_since_prior_order': 29.0},
 4: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '5',
  'orders_day_of_week': 4,
  'order_hour_of_day': 15,
  'days_since_prior_order': 28.0},
 5: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '6',
  'orders_day_of_week': 2,
  'order_hour_of_day': 7,
  'days_since_prior_order': 19.0},
 6: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '7',
  'orders_day_of_week': 1,
  'order_hour_of_day': 9,
  'days_since_prior_order': 20.0},
 7: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '8',
  'orders_day_of_week': 1,
  'order_hour_of_day': 14,
  'days_since_prior_order': 14.0},
 8: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '9',
  'orders_day_of_week': 1,
  'order_hour_of_day': 16,
  'days_since_prior_order': 0.0},
 9: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '10',
  'orders_day_of_week': 4,
  'order_hour_of_day': 8,
  'days_since_prior_order': 30.0},
 10: {'order_id': dtype('O'),
  'user_identity_number': 1,
  'order_number': '11',
  'orders_day_of_week': 4,
  'order_hour_of_day': 8,
  'days_since_prior_order': 14.0},
 11: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '1',
  'orders_day_of_week': 2,
  'order_hour_of_day': 11,
  'days_since_prior_order': nan},
 12: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '2',
  'orders_day_of_week': 5,
  'order_hour_of_day': 10,
  'days_since_prior_order': 10.0},
 13: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '3',
  'orders_day_of_week': 1,
  'order_hour_of_day': 10,
  'days_since_prior_order': 3.0},
 14: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '4',
  'orders_day_of_week': 2,
  'order_hour_of_day': 10,
  'days_since_prior_order': 8.0},
 15: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '5',
  'orders_day_of_week': 3,
  'order_hour_of_day': 11,
  'days_since_prior_order': 8.0},
 16: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '6',
  'orders_day_of_week': 2,
  'order_hour_of_day': 9,
  'days_since_prior_order': 13.0},
 17: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '7',
  'orders_day_of_week': 2,
  'order_hour_of_day': 12,
  'days_since_prior_order': 14.0},
 18: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '8',
  'orders_day_of_week': 1,
  'order_hour_of_day': 15,
  'days_since_prior_order': 27.0},
 19: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '9',
  'orders_day_of_week': 2,
  'order_hour_of_day': 9,
  'days_since_prior_order': 8.0},
 20: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '10',
  'orders_day_of_week': 1,
  'order_hour_of_day': 11,
  'days_since_prior_order': 6.0},
 21: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '11',
  'orders_day_of_week': 1,
  'order_hour_of_day': 10,
  'days_since_prior_order': 30.0},
 22: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '12',
  'orders_day_of_week': 1,
  'order_hour_of_day': 9,
  'days_since_prior_order': 28.0},
 23: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '13',
  'orders_day_of_week': 4,
  'order_hour_of_day': 11,
  'days_since_prior_order': 30.0},
 24: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '14',
  'orders_day_of_week': 3,
  'order_hour_of_day': 10,
  'days_since_prior_order': 13.0},
 25: {'order_id': dtype('O'),
  'user_identity_number': 2,
  'order_number': '15',
  'orders_day_of_week': 1,
  'order_hour_of_day': 11,
  'days_since_prior_order': 30.0},
 26: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '1',
  'orders_day_of_week': 1,
  'order_hour_of_day': 14,
  'days_since_prior_order': nan},
 27: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '2',
  'orders_day_of_week': 3,
  'order_hour_of_day': 19,
  'days_since_prior_order': 9.0},
 28: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '3',
  'orders_day_of_week': 3,
  'order_hour_of_day': 16,
  'days_since_prior_order': 21.0},
 29: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '4',
  'orders_day_of_week': 2,
  'order_hour_of_day': 18,
  'days_since_prior_order': 20.0},
 30: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '5',
  'orders_day_of_week': 0,
  'order_hour_of_day': 17,
  'days_since_prior_order': 12.0},
 31: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '6',
  'orders_day_of_week': 0,
  'order_hour_of_day': 16,
  'days_since_prior_order': 7.0},
 32: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '7',
  'orders_day_of_week': 0,
  'order_hour_of_day': 15,
  'days_since_prior_order': 7.0},
 33: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '8',
  'orders_day_of_week': 0,
  'order_hour_of_day': 17,
  'days_since_prior_order': 7.0},
 34: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '9',
  'orders_day_of_week': 0,
  'order_hour_of_day': 16,
  'days_since_prior_order': 7.0},
 35: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '10',
  'orders_day_of_week': 3,
  'order_hour_of_day': 16,
  'days_since_prior_order': 17.0},
 36: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '11',
  'orders_day_of_week': 0,
  'order_hour_of_day': 18,
  'days_since_prior_order': 11.0},
 37: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '12',
  'orders_day_of_week': 1,
  'order_hour_of_day': 15,
  'days_since_prior_order': 15.0},
 38: {'order_id': dtype('O'),
  'user_identity_number': 3,
  'order_number': '13',
  'orders_day_of_week': 5,
  'order_hour_of_day': 15,
  'days_since_prior_order': 11.0},
 39: {'order_id': dtype('O'),
  'user_identity_number': 4,
  'order_number': '1',
  'orders_day_of_week': 6,
  'order_hour_of_day': 11,
  'days_since_prior_order': nan},
 40: {'order_id': dtype('O'),
  'user_identity_number': 4,
  'order_number': '2',
  'orders_day_of_week': 4,
  'order_hour_of_day': 11,
  'days_since_prior_order': 19.0},
 41: {'order_id': dtype('O'),
  'user_identity_number': 4,
  'order_number': '3',
  'orders_day_of_week': 4,
  'order_hour_of_day': 15,
  'days_since_prior_order': 21.0},
 42: {'order_id': dtype('O'),
  'user_identity_number': 4,
  'order_number': '4',
  'orders_day_of_week': 5,
  'order_hour_of_day': 13,
  'days_since_prior_order': 15.0},
 43: {'order_id': dtype('O'),
  'user_identity_number': 4,
  'order_number': '5',
  'orders_day_of_week': 5,
  'order_hour_of_day': 13,
  'days_since_prior_order': 0.0},
 44: {'order_id': dtype('O'),
  'user_identity_number': 4,
  'order_number': '6',
  'orders_day_of_week': 3,
  'order_hour_of_day': 12,
  'days_since_prior_order': 30.0},
 45: {'order_id': dtype('O'),
  'user_identity_number': 5,
  'order_number': '1',
  'orders_day_of_week': 3,
  'order_hour_of_day': 12,
  'days_since_prior_order': nan},
 46: {'order_id': dtype('O'),
  'user_identity_number': 5,
  'order_number': '2',
  'orders_day_of_week': 0,
  'order_hour_of_day': 16,
  'days_since_prior_order': 11.0},
 47: {'order_id': dtype('O'),
  'user_identity_number': 5,
  'order_number': '3',
  'orders_day_of_week': 3,
  'order_hour_of_day': 18,
  'days_since_prior_order': 10.0},
 48: {'order_id': dtype('O'),
  'user_identity_number': 5,
  'order_number': '4',
  'orders_day_of_week': 1,
  'order_hour_of_day': 18,
  'days_since_prior_order': 19.0},
 49: {'order_id': dtype('O'),
  'user_identity_number': 5,
  'order_number': '5',
  'orders_day_of_week': 0,
  'order_hour_of_day': 11,
  'days_since_prior_order': 6.0},
 50: {'order_id': dtype('O'),
  'user_identity_number': 6,
  'order_number': '1',
  'orders_day_of_week': 5,
  'order_hour_of_day': 18,
  'days_since_prior_order': nan},
 51: {'order_id': dtype('O'),
  'user_identity_number': 6,
  'order_number': '2',
  'orders_day_of_week': 4,
  'order_hour_of_day': 16,
  'days_since_prior_order': 6.0},
 52: {'order_id': dtype('O'),
  'user_identity_number': 6,
  'order_number': '3',
  'orders_day_of_week': 2,
  'order_hour_of_day': 18,
  'days_since_prior_order': 12.0},
 53: {'order_id': dtype('O'),
  'user_identity_number': 6,
  'order_number': '4',
  'orders_day_of_week': 3,
  'order_hour_of_day': 16,
  'days_since_prior_order': 22.0},
 54: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '1',
  'orders_day_of_week': 3,
  'order_hour_of_day': 9,
  'days_since_prior_order': nan},
 55: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '2',
  'orders_day_of_week': 1,
  'order_hour_of_day': 19,
  'days_since_prior_order': 30.0},
 56: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '3',
  'orders_day_of_week': 0,
  'order_hour_of_day': 18,
  'days_since_prior_order': 30.0},
 57: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '4',
  'orders_day_of_week': 2,
  'order_hour_of_day': 10,
  'days_since_prior_order': 9.0},
 58: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '5',
  'orders_day_of_week': 5,
  'order_hour_of_day': 18,
  'days_since_prior_order': 3.0},
 59: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '6',
  'orders_day_of_week': 1,
  'order_hour_of_day': 18,
  'days_since_prior_order': 10.0},
 60: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '7',
  'orders_day_of_week': 1,
  'order_hour_of_day': 15,
  'days_since_prior_order': 7.0},
 61: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '8',
  'orders_day_of_week': 2,
  'order_hour_of_day': 12,
  'days_since_prior_order': 8.0},
 62: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '9',
  'orders_day_of_week': 6,
  'order_hour_of_day': 7,
  'days_since_prior_order': 4.0},
 63: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '10',
  'orders_day_of_week': 1,
  'order_hour_of_day': 20,
  'days_since_prior_order': 9.0},
 64: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '11',
  'orders_day_of_week': 0,
  'order_hour_of_day': 15,
  'days_since_prior_order': 6.0},
 65: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '12',
  'orders_day_of_week': 0,
  'order_hour_of_day': 14,
  'days_since_prior_order': 7.0},
 66: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '13',
  'orders_day_of_week': 5,
  'order_hour_of_day': 15,
  'days_since_prior_order': 5.0},
 67: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '14',
  'orders_day_of_week': 1,
  'order_hour_of_day': 13,
  'days_since_prior_order': 17.0},
 68: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '15',
  'orders_day_of_week': 3,
  'order_hour_of_day': 16,
  'days_since_prior_order': 2.0},
 69: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '16',
  'orders_day_of_week': 0,
  'order_hour_of_day': 13,
  'days_since_prior_order': 11.0},
 70: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '17',
  'orders_day_of_week': 0,
  'order_hour_of_day': 10,
  'days_since_prior_order': 28.0},
 71: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '18',
  'orders_day_of_week': 0,
  'order_hour_of_day': 9,
  'days_since_prior_order': 7.0},
 72: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '19',
  'orders_day_of_week': 3,
  'order_hour_of_day': 12,
  'days_since_prior_order': 3.0},
 73: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '20',
  'orders_day_of_week': 3,
  'order_hour_of_day': 9,
  'days_since_prior_order': 7.0},
 74: {'order_id': dtype('O'),
  'user_identity_number': 7,
  'order_number': '21',
  'orders_day_of_week': 2,
  'order_hour_of_day': 11,
  'days_since_prior_order': 6.0},
 75: {'order_id': dtype('O'),
  'user_identity_number': 8,
  'order_number': '1',
  'orders_day_of_week': 6,
  'order_hour_of_day': 0,
  'days_since_prior_order': nan},
 76: {'order_id': dtype('O'),
  'user_identity_number': 8,
  'order_number': '2',
  'orders_day_of_week': 1,
  'order_hour_of_day': 8,
  'days_since_prior_order': 30.0},
 77: {'order_id': dtype('O'),
  'user_identity_number': 8,
  'order_number': '3',
  'orders_day_of_week': 5,
  'order_hour_of_day': 0,
  'days_since_prior_order': 30.0},
 78: {'order_id': dtype('O'),
  'user_identity_number': 8,
  'order_number': '4',
  'orders_day_of_week': 1,
  'order_hour_of_day': 14,
  'days_since_prior_order': 10.0},
 79: {'order_id': dtype('O'),
  'user_identity_number': 9,
  'order_number': '1',
  'orders_day_of_week': 1,
  'order_hour_of_day': 17,
  'days_since_prior_order': nan},
 80: {'order_id': dtype('O'),
  'user_identity_number': 9,
  'order_number': '2',
  'orders_day_of_week': 0,
  'order_hour_of_day': 14,
  'days_since_prior_order': 6.0},
 81: {'order_id': dtype('O'),
  'user_identity_number': 9,
  'order_number': '3',
  'orders_day_of_week': 5,
  'order_hour_of_day': 12,
  'days_since_prior_order': 30.0},
 82: {'order_id': dtype('O'),
  'user_identity_number': 9,
  'order_number': '4',
  'orders_day_of_week': 6,
  'order_hour_of_day': 10,
  'days_since_prior_order': 30.0},
 83: {'order_id': dtype('O'),
  'user_identity_number': 10,
  'order_number': '1',
  'orders_day_of_week': 2,
  'order_hour_of_day': 14,
  'days_since_prior_order': nan},
 84: {'order_id': dtype('O'),
  'user_identity_number': 10,
  'order_number': '2',
  'orders_day_of_week': 5,
  'order_hour_of_day': 15,
  'days_since_prior_order': 30.0},
 85: {'order_id': dtype('O'),
  'user_identity_number': 10,
  'order_number': '3',
  'orders_day_of_week': 3,
  'order_hour_of_day': 19,
  'days_since_prior_order': 12.0},
 86: {'order_id': dtype('O'),
  'user_identity_number': 10,
  'order_number': '4',
  'orders_day_of_week': 3,
  'order_hour_of_day': 15,
  'days_since_prior_order': 14.0},
 87: {'order_id': dtype('O'),
  'user_identity_number': 10,
  'order_number': '5',
  'orders_day_of_week': 5,
  'order_hour_of_day': 20,
  'days_since_prior_order': 23.0},
 88: {'order_id': dtype('O'),
  'user_identity_number': 10,
  'order_number': '6',
  'orders_day_of_week': 0,
  'order_hour_of_day': 19,
  'days_since_prior_order': 30.0},
 89: {'order_id': dtype('O'),
  'user_identity_number': 11,
  'order_number': '1',
  'orders_day_of_week': 0,
  'order_hour_of_day': 11,
  'days_since_prior_order': nan},
 90: {'order_id': dtype('O'),
  'user_identity_number': 11,
  'order_number': '2',
  'orders_day_of_week': 5,
  'order_hour_of_day': 11,
  'days_since_prior_order': 12.0},
 91: {'order_id': dtype('O'),
  'user_identity_number': 11,
  'order_number': '3',
  'orders_day_of_week': 5,
  'order_hour_of_day': 10,
  'days_since_prior_order': 14.0},
 92: {'order_id': dtype('O'),
  'user_identity_number': 11,
  'order_number': '4',
  'orders_day_of_week': 5,
  'order_hour_of_day': 13,
  'days_since_prior_order': 30.0},
 93: {'order_id': dtype('O'),
  'user_identity_number': 11,
  'order_number': '5',
  'orders_day_of_week': 5,
  'order_hour_of_day': 11,
  'days_since_prior_order': 30.0},
 94: {'order_id': dtype('O'),
  'user_identity_number': 11,
  'order_number': '6',
  'orders_day_of_week': 5,
  'order_hour_of_day': 11,
  'days_since_prior_order': 7.0},
 95: {'order_id': dtype('O'),
  'user_identity_number': 11,
  'order_number': '7',
  'orders_day_of_week': 5,
  'order_hour_of_day': 9,
  'days_since_prior_order': 30.0},
 96: {'order_id': dtype('O'),
  'user_identity_number': 11,
  'order_number': '8',
  'orders_day_of_week': 6,
  'order_hour_of_day': 11,
  'days_since_prior_order': 8.0},
 97: {'order_id': dtype('O'),
  'user_identity_number': 12,
  'order_number': '1',
  'orders_day_of_week': 1,
  'order_hour_of_day': 12,
  'days_since_prior_order': nan},
 98: {'order_id': dtype('O'),
  'user_identity_number': 12,
  'order_number': '2',
  'orders_day_of_week': 5,
  'order_hour_of_day': 9,
  'days_since_prior_order': 30.0},
 99: {'order_id': dtype('O'),
  'user_identity_number': 12,
  'order_number': '3',
  'orders_day_of_week': 5,
  'order_hour_of_day': 8,
  'days_since_prior_order': 14.0},
 100: {'order_id': dtype('O'),
  'user_identity_number': 12,
  'order_number': '4',
  'orders_day_of_week': 3,
  'order_hour_of_day': 9,
  'days_since_prior_order': 26.0},
 101: {'order_id': dtype('O'),
  'user_identity_number': 12,
  'order_number': '5',
  'orders_day_of_week': 1,
  'order_hour_of_day': 9,
  'days_since_prior_order': 30.0},
 102: {'order_id': dtype('O'),
  'user_identity_number': 12,
  'order_number': '6',
  'orders_day_of_week': 1,
  'order_hour_of_day': 20,
  'days_since_prior_order': 30.0},
 103: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '1',
  'orders_day_of_week': 6,
  'order_hour_of_day': 12,
  'days_since_prior_order': nan},
 104: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '2',
  'orders_day_of_week': 0,
  'order_hour_of_day': 11,
  'days_since_prior_order': 8.0},
 105: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '3',
  'orders_day_of_week': 6,
  'order_hour_of_day': 21,
  'days_since_prior_order': 6.0},
 106: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '4',
  'orders_day_of_week': 1,
  'order_hour_of_day': 12,
  'days_since_prior_order': 9.0},
 107: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '5',
  'orders_day_of_week': 0,
  'order_hour_of_day': 13,
  'days_since_prior_order': 6.0},
 108: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '6',
  'orders_day_of_week': 0,
  'order_hour_of_day': 18,
  'days_since_prior_order': 7.0},
 109: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '7',
  'orders_day_of_week': 0,
  'order_hour_of_day': 8,
  'days_since_prior_order': 7.0},
 110: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '8',
  'orders_day_of_week': 6,
  'order_hour_of_day': 18,
  'days_since_prior_order': 13.0},
 111: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '9',
  'orders_day_of_week': 6,
  'order_hour_of_day': 17,
  'days_since_prior_order': 7.0},
 112: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '10',
  'orders_day_of_week': 6,
  'order_hour_of_day': 22,
  'days_since_prior_order': 7.0},
 113: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '11',
  'orders_day_of_week': 0,
  'order_hour_of_day': 14,
  'days_since_prior_order': 8.0},
 114: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '12',
  'orders_day_of_week': 6,
  'order_hour_of_day': 13,
  'days_since_prior_order': 6.0},
 115: {'order_id': dtype('O'),
  'user_identity_number': 13,
  'order_number': '13',
  'orders_day_of_week': 0,
  'order_hour_of_day': 21,
  'days_since_prior_order': 8.0},
 116: {'order_id': dtype('O'),
  'user_identity_number': 14,
  'order_number': '1',
  'orders_day_of_week': 2,
  'order_hour_of_day': 18,
  'days_since_prior_order': nan},

In [93]:
 df_orders['user_identity_number']==1

0           True
1           True
2           True
3           True
4           True
           ...
3421078    False
3421079    False
3421080    False
3421081    False
3421082    False
Name: user_identity_number, Length: 3421083, dtype: bool

In [94]:
df_orders[df_orders['user_identity_number']==1]

,order_id,user_identity_number,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,object,1,1,2,8,NaN
1,object,1,2,3,7,15.0
2,object,1,3,3,12,21.0
3,object,1,4,4,7,29.0
4,object,1,5,4,15,28.0
5,object,1,6,2,7,19.0
6,object,1,7,1,9,20.0
7,object,1,8,1,14,14.0
8,object,1,9,1,16,0.0
9,object,1,10,4,8,30.0
10,object,1,11,4,8,14.0

In [96]:
df_user = df_orders[df_orders['user_identity_number']==1]

In [97]:
df_user.head()

,order_id,user_identity_number,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order
0,object,1,1,2,8,NaN
1,object,1,2,3,7,15.0
2,object,1,3,3,12,21.0
3,object,1,4,4,7,29.0
4,object,1,5,4,15,28.0

Question 10
You also need to provide some details about this user’s behavior. What basic stats can you provide based on the information you have?

In [ ]:
The user behavior has a user_id of 1 and his latest order time was 8:00hours while 15 hours his last order time bearing an order number of 5

Question 11
Check the organization and structure of your notebook. Be sure to include section headings and code comments.

In [ ]:
organisation and structure of the notebook checked

In [ ]:
Question 12
Export your df_ords dataframe as “orders_wrangled.csv” in your “Prepared Data” folder.

In [99]:
df_orders.to_csv(os.path.join(path, '02-Data','Prepared Data', 'orders_wrangled.csv'))

In [ ]:
Question 13
Export the df_dep_t_new dataframe as “departments_wrangled.csv” in your “Prepared Data” folder so that you have a “.csv” file 
of your departments data in the correct format.

In [101]:
df_dep_t_new.to_csv(os.path.join(path, '02-Data','Prepared Data', 'departments_wrangled.csv'))